[tool.poetry]
name = "qloader"
version = "4.6.1"
description = "Gather results from some search engine"
authors = ["mgrasker <mgraskertheband@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
selenium = "^3.141.0"
requests = "^2.23.0"
boto3 = "^1.12.5"
pillow = "^7.1.1"
imagehash = "^4.1.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
ipython = "^7.12.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
